In [2]:
import numpy as np
%matplotlib notebook

# Matrix Review

Take the matricies:

$\bf{A} =
\begin{pmatrix}
2 & 4 & -7\\
3 & -3 & 0\\
1 & 7 & 5
\end{pmatrix},\;\;
\bf{B} =
\begin{pmatrix}
2 & 4\\
3 & -3\\
1 & 7
\end{pmatrix}, \;\;
\bf{C} =
\begin{pmatrix}
-1 & 1\\
1 & -1
\end{pmatrix}, \;\;
\bf{D} = 
\begin{pmatrix}
2 & 0\\
-3 & 6
\end{pmatrix}
$ 

Define the matricies as numpy arrays

In [5]:
A = np.array([[ 2,  4, -7],
              [ 3, -3,  0],
              [ 1,  7,  5]])

B = np.array([[ 2,  4],
              [ 3, -3],
              [ 1,  7]])

C = np.array([[-1,  1],
              [ 1, -1]])

D = np.array([[ 2,  0],
              [-3,  6]])

1. Multiply $\bf{A}$ by 2.5 

In [6]:
(2.5)*A

array([[  5. ,  10. , -17.5],
       [  7.5,  -7.5,   0. ],
       [  2.5,  17.5,  12.5]])

2. Evaluate the product of $\bf{C}\cdot\bf{A}$ 

Did you get an error? Do you know why? (Hint: look at the dimensions of the matrix)
- Got an error. the matrices are 2x2 and 3x3, so can't multiply need number of rows to match columns of other 

In [7]:
C*A

ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

3. Evaluate the product of $\bf{C}\cdot\bf{D}$ and then $\bf{D}\cdot\bf{C}$. Do you get the same results? 
- different answers CD != DC

In [21]:
print(np.matmul(C,D))
print()
print(np.matmul(D,C))

print((np.matmul(C,D) == np.matmul(D,C))

[[-5  6]
 [ 5 -6]]

[[-2  2]
 [ 9 -9]]
[[False False]
 [False False]]


4. Find the transpose of $\bf{B}$

In [13]:
B_T = B.T

print("B_T:\n",B_T)

B_T:
 [[ 2  3  1]
 [ 4 -3  7]]


5. Add $\bf{C} + \bf{D}$

In [14]:
C+D

array([[ 1,  1],
       [-2,  5]])

6. Compute the determinate of $\bf{C}$

In [16]:
print(np.linalg.det(C))

0.0


7. Compute the determinate of $\bf{A}$

In [17]:
print(np.linalg.det(A))

-257.9999999999998
